"""initial_tables_accounts_characters_sessions

Revision ID: 14158f02cb30
Revises: 
Create Date: 2026-05-03 09:38:52.148305

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '14158f02cb30'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_table('characters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('world_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('specialisation_path_id', sa.String(), nullable=False),
    sa.Column('ability_scores', sa.JSON(), nullable=False),
    sa.Column('skill_proficiencies', sa.JSON(), nullable=False),
    sa.Column('saving_throw_proficiencies', sa.JSON(), nullable=False),
    sa.Column('hp_current', sa.Integer(), nullable=False),
    sa.Column('hp_max', sa.Integer(), nullable=False),
    sa.Column('ac', sa.Integer(), nullable=False),
    sa.Column('passive_checks', sa.JSON(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('exhaustion_level', sa.Integer(), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=False),
    sa.Column('wallet', sa.JSON(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=False),
    sa.Column('equipped_gear', sa.JSON(), nullable=False),
    sa.Column('known_recipes', sa.JSON(), nullable=False),
    sa.Column('companions', sa.JSON(), nullable=False),
    sa.Column('rp_voice_notes', sa.Text(), nullable=True),
    sa.Column('relationships', sa.JSON(), nullable=False),
    sa.Column('faction_standing', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_player_id'), 'characters', ['player_id'], unique=False)
    op.create_index(op.f('ix_characters_world_id'), 'characters', ['world_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('world_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('session_summary', sa.Text(), nullable=True),
    sa.Column('analytics', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_character_id'), 'sessions', ['character_id'], unique=False)
    op.create_index(op.f('ix_sessions_player_id'), 'sessions', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_player_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_character_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_characters_world_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_player_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
