"""add pending_turns table

Revision ID: 4a9b5c845fe9
Revises: b7aef85c258f
Create Date: 2026-05-03 13:47:01.044832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a9b5c845fe9'
down_revision: Union[str, Sequence[str], None] = 'b7aef85c258f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_turns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('npc_id', sa.String(), nullable=False),
    sa.Column('turn_type', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('player_input', sa.Text(), nullable=False),
    sa.Column('character_snapshot', sa.JSON(), nullable=True),
    sa.Column('analysis_result', sa.JSON(), nullable=True),
    sa.Column('check_results', sa.JSON(), nullable=True),
    sa.Column('animation_directives', sa.JSON(), nullable=True),
    sa.Column('scene_changes', sa.JSON(), nullable=True),
    sa.Column('final_response', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_turns_player_id'), 'pending_turns', ['player_id'], unique=False)
    op.create_index(op.f('ix_pending_turns_scene_id'), 'pending_turns', ['scene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_turns_scene_id'), table_name='pending_turns')
    op.drop_index(op.f('ix_pending_turns_player_id'), table_name='pending_turns')
    op.drop_table('pending_turns')
    # ### end Alembic commands ###
