"""add transaction_log table

Revision ID: 7bc64702df81
Revises: 4a9b5c845fe9
Create Date: 2026-05-05 19:36:21.973814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc64702df81'
down_revision: Union[str, Sequence[str], None] = '4a9b5c845fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('world_id', sa.String(), nullable=False),
    sa.Column('tx_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('item_quantity', sa.Integer(), nullable=True),
    sa.Column('npc_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('base_price', sa.Integer(), nullable=True),
    sa.Column('markup_pct', sa.Float(), nullable=True),
    sa.Column('faction_modifier', sa.Float(), nullable=True),
    sa.Column('sell_back_ratio', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_log_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_log_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_log_player_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_log_character_id'))

    op.drop_table('transaction_log')
    # ### end Alembic commands ###
