"""add scenes table

Revision ID: b7aef85c258f
Revises: 14158f02cb30
Create Date: 2026-05-03 13:32:08.634687

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7aef85c258f'
down_revision: str | Sequence[str] | None = '14158f02cb30'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('npc_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scene_state', sa.JSON(), nullable=False),
    sa.Column('turn_history', sa.JSON(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('scene_summary', sa.Text(), nullable=True),
    sa.Column('analytics', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_session_id'), 'scenes', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenes_session_id'), table_name='scenes')
    op.drop_table('scenes')
    # ### end Alembic commands ###
